version: "3.9"

services:
  gtf-blog:
    build: .
    container_name: gtf-blog
    restart: always
    ports:
      - "4040:5001"
    env_file:
      - .env
    networks:
      - shared-network
    volumes:
      - uploads_data:/src/uploads

networks:
  shared-network:
    external: true
    name: eldecogroup-backend_eldeco-network

volumes:
  uploads_data: